from pydantic import BaseModel, Field
from typing import List

class TrainingInstance(BaseModel):
    """This is an instance of training data for the model.
    It contains a sentence and the state sequence for the sentence that will be used to train the hmm.
    """
    sentence: str = Field(description="The sentence that was generated by the model")
    state_sequence: List[str] = Field(default_factory=list, description="The state sequence for the sentence, each state will correspond to the word in the sentence. States can be A, D, P, W")
    sentence_indexes: List[int] = Field(default_factory=list, description="The indexes of the words in the sentence")
    state_sequence_indexes: List[int] = Field(default_factory=list, description="The indexes of the states in the state sequence")

class TrainingData(BaseModel):
    """This will be the training data for the model.
    It will contain a list of training instances.
    """
    instances: List[TrainingInstance] = Field(description="The training instances")
